/// A nonempty fragment emitted during text generation.
public struct TextDelta: Hashable, Sendable {
    /// The exact fragment generated by the backend.
    public let text: String

    /// Creates a nonempty generated-text fragment.
    public init(_ text: String) throws {
        guard !text.isEmpty else {
            throw InferenceValidationError.emptyTextDelta
        }
        self.text = text
    }
}

/// Measured token counts for a completed generation.
public struct TokenUsage: Hashable, Sendable {
    /// The number of prompt tokens processed.
    public let promptTokens: UInt32

    /// The number of output tokens generated.
    public let outputTokens: UInt32

    /// Creates measured token usage.
    public init(promptTokens: UInt32, outputTokens: UInt32) {
        self.promptTokens = promptTokens
        self.outputTokens = outputTokens
    }
}

/// The reason a backend completed generation successfully.
public enum GenerationFinishReason: String, Sendable {
    /// The backend encountered a model stop condition.
    case stop

    /// The request's maximum output token count was reached.
    case maximumTokens
}

/// The authoritative successful result of one inference attempt.
public struct GenerationResult: Hashable, Sendable {
    /// The complete generated text, independent of streamed delta boundaries.
    public let fullText: String

    /// The exact model revision used to produce the result.
    public let modelUsed: ModelReference

    /// Why generation completed.
    public let finishReason: GenerationFinishReason

    /// Measured prompt and output token counts.
    public let usage: TokenUsage

    /// Creates a complete generation result.
    public init(
        fullText: String,
        modelUsed: ModelReference,
        finishReason: GenerationFinishReason,
        usage: TokenUsage
    ) {
        self.fullText = fullText
        self.modelUsed = modelUsed
        self.finishReason = finishReason
        self.usage = usage
    }
}

/// A backend event emitted while executing one attempt.
public enum GenerationEvent: Hashable, Sendable {
    /// A nonempty fragment of generated text.
    case textDelta(TextDelta)

    /// The single successful terminal result.
    case completed(GenerationResult)
}
